[tox]
envlist = py311-django{42}

[pycodestyle]
exclude = .git,.tox,migrations
max-line-length = 120

[pytest]
DJANGO_SETTINGS_MODULE = openedx_auto_enroll.settings.test
addopts = --cov openedx_auto_enroll --cov-report term-missing
norecursedirs = .* docs requirements site-packages

[testenv]
deps =
    django42: Django>=4.2,<4.3
    -r{toxinidir}/requirements/test.in
commands =
    pytest {posargs}
